security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    MapBundle\Document\User:
     algorithm: bcrypt
     cost: 12

  role_hierarchy:
    ROLE_ADMIN:        ROLE_USER
    ROLE_ORGANIZATION_ADMIN: ROLE_USER
    ROLE_API:        ROLE_USER
    ROLE_SUPER_ADMIN:    [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    my_mongo_provider:
      mongodb: {class: MapBundle\Document\User, property: email}
    in_memory:
      memory:
        users:
          restapi:  { password: secretpw, roles: [ 'ROLE_API' ] }

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern:   ^/api/(login|doc)
      stateless: true
      anonymous: ~

    api:
      pattern:   ^/api
      stateless: true
      lexik_jwt: ~

    main:
      pattern: ^/
      anonymous: ~
      stateless: true

  access_control:
    - { path: ^/api/(logins|doc), roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

