security:
  encoders:
    MapBundle\Document\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:        ROLE_USER

  providers:
    my_mongo_provider:
      mongodb: {class: MapBundle\Document\User, property: email}

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern:   ^/api/(login|doc)
      stateless: true
      anonymous: ~

    api:
      pattern:   ^/api
      stateless: true
      lexik_jwt: ~

    main:
      pattern: ^/
      anonymous: ~
      stateless: true

  access_control:
    - { path: ^/api/(logins|doc), roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

