map_homepage:
  path: /hello/{name}
  defaults: { _controller: MapBundle:Default:index }

contents:
  resource: "map.controller.contents"
  type: rest

teams:
  resource: "map.controller.teams"
  type: rest

users:
  resource: "map.controller.users"
  type: rest

auth:
  resource: "map.controller.auth"
  type: rest