services:
  map.controller.contents:
    class: MapBundle\Controller\ContentsController
    arguments: [@doctrine_mongodb]
    calls:
          - [setContainer, ["@service_container"]]

  map.controller.users:
    class: MapBundle\Controller\UsersController
    arguments: [@doctrine_mongodb]
    calls:
          - [setContainer, ["@service_container"]]

  map.controller.teams:
    class: MapBundle\Controller\TeamsController
    arguments: [@doctrine_mongodb]
    calls:
          - [setContainer, ["@service_container"]]

  map.controller.skills:
    class: MapBundle\Controller\SkillsController
    arguments: [@doctrine_mongodb]
    calls:
          - [setContainer, ["@service_container"]]

  map.controller.events:
    class: MapBundle\Controller\EventsController
    arguments: [@doctrine_mongodb]
    calls:
          - [setContainer, ["@service_container"]]

  map.controller.auth:
    class: MapBundle\Controller\AuthController
    arguments: [@doctrine_mongodb]
    calls:
      - [setContainer, ["@service_container"]]

  encoder.bcrypt:
    class: Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder
    arguments: [12]

  validator.encoded_equal_to:
    class: MapBundle\Validator\Constraints\EncodedEqualToValidator
    tags:
      - { name: validator.constraint_validator, alias: encoded_equal_to }
    arguments: ["@encoder.bcrypt"]

  security.access.user_voter:
    class:    MapBundle\Security\Authorization\Voter\UserVoter
    public:   false
    tags:
      - { name: security.voter }

  security.access.team_voter:
    class:    MapBundle\Security\Authorization\Voter\TeamVoter
    public:   false
    tags:
      - { name: security.voter }

  security.access.content_voter:
    class:    MapBundle\Security\Authorization\Voter\ContentVoter
    public:   false
    tags:
      - { name: security.voter }

  security.access.skill_voter:
      class:    MapBundle\Security\Authorization\Voter\SkillVoter
      public:   false
      tags:
        - { name: security.voter }

  map.log_formatter:
    class: Monolog\Formatter\LineFormatter
    calls:
      - [includeStacktraces]